// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: discovery_service.proto

package user_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiscoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryRequest) Reset() {
	*x = DiscoveryRequest{}
	mi := &file_discovery_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryRequest) ProtoMessage() {}

func (x *DiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryRequest.ProtoReflect.Descriptor instead.
func (*DiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_discovery_service_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoveryRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type ServiceInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInstance) Reset() {
	*x = ServiceInstance{}
	mi := &file_discovery_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInstance) ProtoMessage() {}

func (x *ServiceInstance) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInstance.ProtoReflect.Descriptor instead.
func (*ServiceInstance) Descriptor() ([]byte, []int) {
	return file_discovery_service_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceInstance) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServiceInstance) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_discovery_service_proto protoreflect.FileDescriptor

const file_discovery_service_proto_rawDesc = "" +
	"\n" +
	"\x17discovery_service.proto\x12\x19backend.discovery_service\"5\n" +
	"\x10DiscoveryRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"9\n" +
	"\x0fServiceInstance\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port2y\n" +
	"\x10DiscoveryService\x12e\n" +
	"\bDiscover\x12+.backend.discovery_service.DiscoveryRequest\x1a*.backend.discovery_service.ServiceInstance\"\x00B%Z#github.com/TripConnect/user-serviceb\x06proto3"

var (
	file_discovery_service_proto_rawDescOnce sync.Once
	file_discovery_service_proto_rawDescData []byte
)

func file_discovery_service_proto_rawDescGZIP() []byte {
	file_discovery_service_proto_rawDescOnce.Do(func() {
		file_discovery_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discovery_service_proto_rawDesc), len(file_discovery_service_proto_rawDesc)))
	})
	return file_discovery_service_proto_rawDescData
}

var file_discovery_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_discovery_service_proto_goTypes = []any{
	(*DiscoveryRequest)(nil), // 0: backend.discovery_service.DiscoveryRequest
	(*ServiceInstance)(nil),  // 1: backend.discovery_service.ServiceInstance
}
var file_discovery_service_proto_depIdxs = []int32{
	0, // 0: backend.discovery_service.DiscoveryService.Discover:input_type -> backend.discovery_service.DiscoveryRequest
	1, // 1: backend.discovery_service.DiscoveryService.Discover:output_type -> backend.discovery_service.ServiceInstance
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_discovery_service_proto_init() }
func file_discovery_service_proto_init() {
	if File_discovery_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discovery_service_proto_rawDesc), len(file_discovery_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discovery_service_proto_goTypes,
		DependencyIndexes: file_discovery_service_proto_depIdxs,
		MessageInfos:      file_discovery_service_proto_msgTypes,
	}.Build()
	File_discovery_service_proto = out.File
	file_discovery_service_proto_goTypes = nil
	file_discovery_service_proto_depIdxs = nil
}
