// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: livestream_service.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LivestreamService_CreateLivestream_FullMethodName = "/backend.livestream_service.LivestreamService/CreateLivestream"
	LivestreamService_EndLivestream_FullMethodName    = "/backend.livestream_service.LivestreamService/EndLivestream"
	LivestreamService_FindLivestream_FullMethodName   = "/backend.livestream_service.LivestreamService/FindLivestream"
	LivestreamService_SearchLivestream_FullMethodName = "/backend.livestream_service.LivestreamService/SearchLivestream"
)

// LivestreamServiceClient is the client API for LivestreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LivestreamServiceClient interface {
	CreateLivestream(ctx context.Context, in *CreateLivestreamRequest, opts ...grpc.CallOption) (*Livestream, error)
	EndLivestream(ctx context.Context, in *EndLivestreamRequest, opts ...grpc.CallOption) (*Livestream, error)
	FindLivestream(ctx context.Context, in *FindLivestreamRequest, opts ...grpc.CallOption) (*Livestream, error)
	SearchLivestream(ctx context.Context, in *SearchLivestreamsRequest, opts ...grpc.CallOption) (*Livestreams, error)
}

type livestreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLivestreamServiceClient(cc grpc.ClientConnInterface) LivestreamServiceClient {
	return &livestreamServiceClient{cc}
}

func (c *livestreamServiceClient) CreateLivestream(ctx context.Context, in *CreateLivestreamRequest, opts ...grpc.CallOption) (*Livestream, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Livestream)
	err := c.cc.Invoke(ctx, LivestreamService_CreateLivestream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *livestreamServiceClient) EndLivestream(ctx context.Context, in *EndLivestreamRequest, opts ...grpc.CallOption) (*Livestream, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Livestream)
	err := c.cc.Invoke(ctx, LivestreamService_EndLivestream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *livestreamServiceClient) FindLivestream(ctx context.Context, in *FindLivestreamRequest, opts ...grpc.CallOption) (*Livestream, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Livestream)
	err := c.cc.Invoke(ctx, LivestreamService_FindLivestream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *livestreamServiceClient) SearchLivestream(ctx context.Context, in *SearchLivestreamsRequest, opts ...grpc.CallOption) (*Livestreams, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Livestreams)
	err := c.cc.Invoke(ctx, LivestreamService_SearchLivestream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LivestreamServiceServer is the server API for LivestreamService service.
// All implementations must embed UnimplementedLivestreamServiceServer
// for forward compatibility.
type LivestreamServiceServer interface {
	CreateLivestream(context.Context, *CreateLivestreamRequest) (*Livestream, error)
	EndLivestream(context.Context, *EndLivestreamRequest) (*Livestream, error)
	FindLivestream(context.Context, *FindLivestreamRequest) (*Livestream, error)
	SearchLivestream(context.Context, *SearchLivestreamsRequest) (*Livestreams, error)
	mustEmbedUnimplementedLivestreamServiceServer()
}

// UnimplementedLivestreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLivestreamServiceServer struct{}

func (UnimplementedLivestreamServiceServer) CreateLivestream(context.Context, *CreateLivestreamRequest) (*Livestream, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLivestream not implemented")
}
func (UnimplementedLivestreamServiceServer) EndLivestream(context.Context, *EndLivestreamRequest) (*Livestream, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndLivestream not implemented")
}
func (UnimplementedLivestreamServiceServer) FindLivestream(context.Context, *FindLivestreamRequest) (*Livestream, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindLivestream not implemented")
}
func (UnimplementedLivestreamServiceServer) SearchLivestream(context.Context, *SearchLivestreamsRequest) (*Livestreams, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchLivestream not implemented")
}
func (UnimplementedLivestreamServiceServer) mustEmbedUnimplementedLivestreamServiceServer() {}
func (UnimplementedLivestreamServiceServer) testEmbeddedByValue()                           {}

// UnsafeLivestreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LivestreamServiceServer will
// result in compilation errors.
type UnsafeLivestreamServiceServer interface {
	mustEmbedUnimplementedLivestreamServiceServer()
}

func RegisterLivestreamServiceServer(s grpc.ServiceRegistrar, srv LivestreamServiceServer) {
	// If the following call pancis, it indicates UnimplementedLivestreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LivestreamService_ServiceDesc, srv)
}

func _LivestreamService_CreateLivestream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLivestreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LivestreamServiceServer).CreateLivestream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LivestreamService_CreateLivestream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LivestreamServiceServer).CreateLivestream(ctx, req.(*CreateLivestreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LivestreamService_EndLivestream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndLivestreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LivestreamServiceServer).EndLivestream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LivestreamService_EndLivestream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LivestreamServiceServer).EndLivestream(ctx, req.(*EndLivestreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LivestreamService_FindLivestream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindLivestreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LivestreamServiceServer).FindLivestream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LivestreamService_FindLivestream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LivestreamServiceServer).FindLivestream(ctx, req.(*FindLivestreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LivestreamService_SearchLivestream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchLivestreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LivestreamServiceServer).SearchLivestream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LivestreamService_SearchLivestream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LivestreamServiceServer).SearchLivestream(ctx, req.(*SearchLivestreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LivestreamService_ServiceDesc is the grpc.ServiceDesc for LivestreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LivestreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backend.livestream_service.LivestreamService",
	HandlerType: (*LivestreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLivestream",
			Handler:    _LivestreamService_CreateLivestream_Handler,
		},
		{
			MethodName: "EndLivestream",
			Handler:    _LivestreamService_EndLivestream_Handler,
		},
		{
			MethodName: "FindLivestream",
			Handler:    _LivestreamService_FindLivestream_Handler,
		},
		{
			MethodName: "SearchLivestream",
			Handler:    _LivestreamService_SearchLivestream_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "livestream_service.proto",
}
