// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: livestream_service.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Livestream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,4,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	HlsLink       string                 `protobuf:"bytes,5,opt,name=hls_link,json=hlsLink,proto3" json:"hls_link,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Livestream) Reset() {
	*x = Livestream{}
	mi := &file_livestream_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Livestream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Livestream) ProtoMessage() {}

func (x *Livestream) ProtoReflect() protoreflect.Message {
	mi := &file_livestream_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Livestream.ProtoReflect.Descriptor instead.
func (*Livestream) Descriptor() ([]byte, []int) {
	return file_livestream_service_proto_rawDescGZIP(), []int{0}
}

func (x *Livestream) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Livestream) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Livestream) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Livestream) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *Livestream) GetHlsLink() string {
	if x != nil {
		return x.HlsLink
	}
	return ""
}

func (x *Livestream) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type Livestreams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Livestreams   *Livestream            `protobuf:"bytes,1,opt,name=livestreams,proto3" json:"livestreams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Livestreams) Reset() {
	*x = Livestreams{}
	mi := &file_livestream_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Livestreams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Livestreams) ProtoMessage() {}

func (x *Livestreams) ProtoReflect() protoreflect.Message {
	mi := &file_livestream_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Livestreams.ProtoReflect.Descriptor instead.
func (*Livestreams) Descriptor() ([]byte, []int) {
	return file_livestream_service_proto_rawDescGZIP(), []int{1}
}

func (x *Livestreams) GetLivestreams() *Livestream {
	if x != nil {
		return x.Livestreams
	}
	return nil
}

type CreateLivestreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,2,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLivestreamRequest) Reset() {
	*x = CreateLivestreamRequest{}
	mi := &file_livestream_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLivestreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLivestreamRequest) ProtoMessage() {}

func (x *CreateLivestreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livestream_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLivestreamRequest.ProtoReflect.Descriptor instead.
func (*CreateLivestreamRequest) Descriptor() ([]byte, []int) {
	return file_livestream_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLivestreamRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLivestreamRequest) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

type SearchConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          string                 `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchConversationsRequest) Reset() {
	*x = SearchConversationsRequest{}
	mi := &file_livestream_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchConversationsRequest) ProtoMessage() {}

func (x *SearchConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livestream_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchConversationsRequest.ProtoReflect.Descriptor instead.
func (*SearchConversationsRequest) Descriptor() ([]byte, []int) {
	return file_livestream_service_proto_rawDescGZIP(), []int{3}
}

func (x *SearchConversationsRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *SearchConversationsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type FindLivestreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LivestreamId  string                 `protobuf:"bytes,1,opt,name=livestream_id,json=livestreamId,proto3" json:"livestream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindLivestreamRequest) Reset() {
	*x = FindLivestreamRequest{}
	mi := &file_livestream_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindLivestreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindLivestreamRequest) ProtoMessage() {}

func (x *FindLivestreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livestream_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindLivestreamRequest.ProtoReflect.Descriptor instead.
func (*FindLivestreamRequest) Descriptor() ([]byte, []int) {
	return file_livestream_service_proto_rawDescGZIP(), []int{4}
}

func (x *FindLivestreamRequest) GetLivestreamId() string {
	if x != nil {
		return x.LivestreamId
	}
	return ""
}

type EndLivestreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LivestreamId  string                 `protobuf:"bytes,1,opt,name=livestream_id,json=livestreamId,proto3" json:"livestream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndLivestreamRequest) Reset() {
	*x = EndLivestreamRequest{}
	mi := &file_livestream_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndLivestreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndLivestreamRequest) ProtoMessage() {}

func (x *EndLivestreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livestream_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndLivestreamRequest.ProtoReflect.Descriptor instead.
func (*EndLivestreamRequest) Descriptor() ([]byte, []int) {
	return file_livestream_service_proto_rawDescGZIP(), []int{5}
}

func (x *EndLivestreamRequest) GetLivestreamId() string {
	if x != nil {
		return x.LivestreamId
	}
	return ""
}

var File_livestream_service_proto protoreflect.FileDescriptor

const file_livestream_service_proto_rawDesc = "" +
	"\n" +
	"\x18livestream_service.proto\x12\x1abackend.livestream_service\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x01\n" +
	"\n" +
	"Livestream\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1c\n" +
	"\tthumbnail\x18\x04 \x01(\tR\tthumbnail\x12\x19\n" +
	"\bhls_link\x18\x05 \x01(\tR\ahlsLink\x12;\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\"W\n" +
	"\vLivestreams\x12H\n" +
	"\vlivestreams\x18\x01 \x01(\v2&.backend.livestream_service.LivestreamR\vlivestreams\"M\n" +
	"\x17CreateLivestreamRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1c\n" +
	"\tthumbnail\x18\x02 \x01(\tR\tthumbnail\"H\n" +
	"\x1aSearchConversationsRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\tR\x04term\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"<\n" +
	"\x15FindLivestreamRequest\x12#\n" +
	"\rlivestream_id\x18\x01 \x01(\tR\flivestreamId\";\n" +
	"\x14EndLivestreamRequest\x12#\n" +
	"\rlivestream_id\x18\x01 \x01(\tR\flivestreamId2\xd3\x03\n" +
	"\vChatService\x12q\n" +
	"\x10CreateLivestream\x123.backend.livestream_service.CreateLivestreamRequest\x1a&.backend.livestream_service.Livestream\"\x00\x12k\n" +
	"\rEndLivestream\x120.backend.livestream_service.EndLivestreamRequest\x1a&.backend.livestream_service.Livestream\"\x00\x12m\n" +
	"\x0eFindLivestream\x121.backend.livestream_service.FindLivestreamRequest\x1a&.backend.livestream_service.Livestream\"\x00\x12u\n" +
	"\x10SearchLivestream\x126.backend.livestream_service.SearchConversationsRequest\x1a'.backend.livestream_service.Livestreams\"\x00B2Z0github.com/TripConnect/livestream_service;protosb\x06proto3"

var (
	file_livestream_service_proto_rawDescOnce sync.Once
	file_livestream_service_proto_rawDescData []byte
)

func file_livestream_service_proto_rawDescGZIP() []byte {
	file_livestream_service_proto_rawDescOnce.Do(func() {
		file_livestream_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_livestream_service_proto_rawDesc), len(file_livestream_service_proto_rawDesc)))
	})
	return file_livestream_service_proto_rawDescData
}

var file_livestream_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_livestream_service_proto_goTypes = []any{
	(*Livestream)(nil),                 // 0: backend.livestream_service.Livestream
	(*Livestreams)(nil),                // 1: backend.livestream_service.Livestreams
	(*CreateLivestreamRequest)(nil),    // 2: backend.livestream_service.CreateLivestreamRequest
	(*SearchConversationsRequest)(nil), // 3: backend.livestream_service.SearchConversationsRequest
	(*FindLivestreamRequest)(nil),      // 4: backend.livestream_service.FindLivestreamRequest
	(*EndLivestreamRequest)(nil),       // 5: backend.livestream_service.EndLivestreamRequest
	(*timestamppb.Timestamp)(nil),      // 6: google.protobuf.Timestamp
}
var file_livestream_service_proto_depIdxs = []int32{
	6, // 0: backend.livestream_service.Livestream.create_time:type_name -> google.protobuf.Timestamp
	0, // 1: backend.livestream_service.Livestreams.livestreams:type_name -> backend.livestream_service.Livestream
	2, // 2: backend.livestream_service.ChatService.CreateLivestream:input_type -> backend.livestream_service.CreateLivestreamRequest
	5, // 3: backend.livestream_service.ChatService.EndLivestream:input_type -> backend.livestream_service.EndLivestreamRequest
	4, // 4: backend.livestream_service.ChatService.FindLivestream:input_type -> backend.livestream_service.FindLivestreamRequest
	3, // 5: backend.livestream_service.ChatService.SearchLivestream:input_type -> backend.livestream_service.SearchConversationsRequest
	0, // 6: backend.livestream_service.ChatService.CreateLivestream:output_type -> backend.livestream_service.Livestream
	0, // 7: backend.livestream_service.ChatService.EndLivestream:output_type -> backend.livestream_service.Livestream
	0, // 8: backend.livestream_service.ChatService.FindLivestream:output_type -> backend.livestream_service.Livestream
	1, // 9: backend.livestream_service.ChatService.SearchLivestream:output_type -> backend.livestream_service.Livestreams
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_livestream_service_proto_init() }
func file_livestream_service_proto_init() {
	if File_livestream_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_livestream_service_proto_rawDesc), len(file_livestream_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_livestream_service_proto_goTypes,
		DependencyIndexes: file_livestream_service_proto_depIdxs,
		MessageInfos:      file_livestream_service_proto_msgTypes,
	}.Build()
	File_livestream_service_proto = out.File
	file_livestream_service_proto_goTypes = nil
	file_livestream_service_proto_depIdxs = nil
}
