// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: twofa_service.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidationStatus int32

const (
	ValidationStatus_INVALID ValidationStatus = 0
	ValidationStatus_VALID   ValidationStatus = 1
)

// Enum value maps for ValidationStatus.
var (
	ValidationStatus_name = map[int32]string{
		0: "INVALID",
		1: "VALID",
	}
	ValidationStatus_value = map[string]int32{
		"INVALID": 0,
		"VALID":   1,
	}
)

func (x ValidationStatus) Enum() *ValidationStatus {
	p := new(ValidationStatus)
	*p = x
	return p
}

func (x ValidationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_twofa_service_proto_enumTypes[0].Descriptor()
}

func (ValidationStatus) Type() protoreflect.EnumType {
	return &file_twofa_service_proto_enumTypes[0]
}

func (x ValidationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidationStatus.Descriptor instead.
func (ValidationStatus) EnumDescriptor() ([]byte, []int) {
	return file_twofa_service_proto_rawDescGZIP(), []int{0}
}

type Generate2FaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generate2FaRequest) Reset() {
	*x = Generate2FaRequest{}
	mi := &file_twofa_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generate2FaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generate2FaRequest) ProtoMessage() {}

func (x *Generate2FaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generate2FaRequest.ProtoReflect.Descriptor instead.
func (*Generate2FaRequest) Descriptor() ([]byte, []int) {
	return file_twofa_service_proto_rawDescGZIP(), []int{0}
}

func (x *Generate2FaRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type Generate2FaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	QrCode        string                 `protobuf:"bytes,2,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generate2FaResponse) Reset() {
	*x = Generate2FaResponse{}
	mi := &file_twofa_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generate2FaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generate2FaResponse) ProtoMessage() {}

func (x *Generate2FaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generate2FaResponse.ProtoReflect.Descriptor instead.
func (*Generate2FaResponse) Descriptor() ([]byte, []int) {
	return file_twofa_service_proto_rawDescGZIP(), []int{1}
}

func (x *Generate2FaResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Generate2FaResponse) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

type Create2FaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Secret        string                 `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	Otp           string                 `protobuf:"bytes,4,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Create2FaRequest) Reset() {
	*x = Create2FaRequest{}
	mi := &file_twofa_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Create2FaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create2FaRequest) ProtoMessage() {}

func (x *Create2FaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create2FaRequest.ProtoReflect.Descriptor instead.
func (*Create2FaRequest) Descriptor() ([]byte, []int) {
	return file_twofa_service_proto_rawDescGZIP(), []int{2}
}

func (x *Create2FaRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *Create2FaRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Create2FaRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Create2FaRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type Create2FaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Create2FaResponse) Reset() {
	*x = Create2FaResponse{}
	mi := &file_twofa_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Create2FaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create2FaResponse) ProtoMessage() {}

func (x *Create2FaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create2FaResponse.ProtoReflect.Descriptor instead.
func (*Create2FaResponse) Descriptor() ([]byte, []int) {
	return file_twofa_service_proto_rawDescGZIP(), []int{3}
}

func (x *Create2FaResponse) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type Validate2FaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Otp           string                 `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Validate2FaRequest) Reset() {
	*x = Validate2FaRequest{}
	mi := &file_twofa_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Validate2FaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validate2FaRequest) ProtoMessage() {}

func (x *Validate2FaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validate2FaRequest.ProtoReflect.Descriptor instead.
func (*Validate2FaRequest) Descriptor() ([]byte, []int) {
	return file_twofa_service_proto_rawDescGZIP(), []int{4}
}

func (x *Validate2FaRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *Validate2FaRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type Validate2FaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Status        ValidationStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=backend.twofa_service.ValidationStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Validate2FaResponse) Reset() {
	*x = Validate2FaResponse{}
	mi := &file_twofa_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Validate2FaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validate2FaResponse) ProtoMessage() {}

func (x *Validate2FaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_twofa_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validate2FaResponse.ProtoReflect.Descriptor instead.
func (*Validate2FaResponse) Descriptor() ([]byte, []int) {
	return file_twofa_service_proto_rawDescGZIP(), []int{5}
}

func (x *Validate2FaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Validate2FaResponse) GetStatus() ValidationStatus {
	if x != nil {
		return x.Status
	}
	return ValidationStatus_INVALID
}

var File_twofa_service_proto protoreflect.FileDescriptor

const file_twofa_service_proto_rawDesc = "" +
	"\n" +
	"\x13twofa_service.proto\x12\x15backend.twofa_service\"*\n" +
	"\x12Generate2faRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\"F\n" +
	"\x13Generate2faResponse\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x17\n" +
	"\aqr_code\x18\x02 \x01(\tR\x06qrCode\"s\n" +
	"\x10Create2faRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x16\n" +
	"\x06secret\x18\x03 \x01(\tR\x06secret\x12\x10\n" +
	"\x03otp\x18\x04 \x01(\tR\x03otp\"4\n" +
	"\x11Create2faResponse\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\"G\n" +
	"\x12Validate2faRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x10\n" +
	"\x03otp\x18\x02 \x01(\tR\x03otp\"p\n" +
	"\x13Validate2faResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12?\n" +
	"\x06status\x18\x02 \x01(\x0e2'.backend.twofa_service.ValidationStatusR\x06status**\n" +
	"\x10ValidationStatus\x12\v\n" +
	"\aINVALID\x10\x00\x12\t\n" +
	"\x05VALID\x10\x012\xdf\x02\n" +
	"\x1eTwoFactorAuthenticationService\x12j\n" +
	"\x0fGenerateSetting\x12).backend.twofa_service.Generate2faRequest\x1a*.backend.twofa_service.Generate2faResponse\"\x00\x12d\n" +
	"\rCreateSetting\x12'.backend.twofa_service.Create2faRequest\x1a(.backend.twofa_service.Create2faResponse\"\x00\x12k\n" +
	"\x10ValidateResource\x12).backend.twofa_service.Validate2faRequest\x1a*.backend.twofa_service.Validate2faResponse\"\x00B-Z+github.com/TripConnect/twofa_service;protosb\x06proto3"

var (
	file_twofa_service_proto_rawDescOnce sync.Once
	file_twofa_service_proto_rawDescData []byte
)

func file_twofa_service_proto_rawDescGZIP() []byte {
	file_twofa_service_proto_rawDescOnce.Do(func() {
		file_twofa_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_twofa_service_proto_rawDesc), len(file_twofa_service_proto_rawDesc)))
	})
	return file_twofa_service_proto_rawDescData
}

var file_twofa_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_twofa_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_twofa_service_proto_goTypes = []any{
	(ValidationStatus)(0),       // 0: backend.twofa_service.ValidationStatus
	(*Generate2FaRequest)(nil),  // 1: backend.twofa_service.Generate2faRequest
	(*Generate2FaResponse)(nil), // 2: backend.twofa_service.Generate2faResponse
	(*Create2FaRequest)(nil),    // 3: backend.twofa_service.Create2faRequest
	(*Create2FaResponse)(nil),   // 4: backend.twofa_service.Create2faResponse
	(*Validate2FaRequest)(nil),  // 5: backend.twofa_service.Validate2faRequest
	(*Validate2FaResponse)(nil), // 6: backend.twofa_service.Validate2faResponse
}
var file_twofa_service_proto_depIdxs = []int32{
	0, // 0: backend.twofa_service.Validate2faResponse.status:type_name -> backend.twofa_service.ValidationStatus
	1, // 1: backend.twofa_service.TwoFactorAuthenticationService.GenerateSetting:input_type -> backend.twofa_service.Generate2faRequest
	3, // 2: backend.twofa_service.TwoFactorAuthenticationService.CreateSetting:input_type -> backend.twofa_service.Create2faRequest
	5, // 3: backend.twofa_service.TwoFactorAuthenticationService.ValidateResource:input_type -> backend.twofa_service.Validate2faRequest
	2, // 4: backend.twofa_service.TwoFactorAuthenticationService.GenerateSetting:output_type -> backend.twofa_service.Generate2faResponse
	4, // 5: backend.twofa_service.TwoFactorAuthenticationService.CreateSetting:output_type -> backend.twofa_service.Create2faResponse
	6, // 6: backend.twofa_service.TwoFactorAuthenticationService.ValidateResource:output_type -> backend.twofa_service.Validate2faResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_twofa_service_proto_init() }
func file_twofa_service_proto_init() {
	if File_twofa_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_twofa_service_proto_rawDesc), len(file_twofa_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_twofa_service_proto_goTypes,
		DependencyIndexes: file_twofa_service_proto_depIdxs,
		EnumInfos:         file_twofa_service_proto_enumTypes,
		MessageInfos:      file_twofa_service_proto_msgTypes,
	}.Build()
	File_twofa_service_proto = out.File
	file_twofa_service_proto_goTypes = nil
	file_twofa_service_proto_depIdxs = nil
}
